### ISSUE TITLE
generalize force searching in backmap.py

### ISSUE THREAD

**Issue by vuqv** [obrien-lab/cg_simtk_protein_folding#1]
Hi Yang

https://github.com/obrien-lab/cg_simtk_protein_folding/blob/431edce73fbd041ee8dee5f1f7d024cd9c738de1/Backmapping/backmap.py#L150

This stuff can be search by force name to be more generalize in case different openMM versions treat it differently:

```
for force in system.getForces():
    if force.getName() == 'CustomNonbondedForce':
        force.setUseSwitchingFunction(True)
        force.setSwitchingDistance(1.8*nanometer)
```

**Comment by yuj179** [comment]
Thank you, Quyen. I have updated the codes that have this issue.

Yang
